### Execute a Command
POST http://{{server}}:8080/remote/cmd/execute
Content-Type: application/json

{
    "cmd": "dir"
}

### Another example - Run a custom command
POST http://{{server}}:8080/remote/cmd/execute
Content-Type: application/json

{
    "cmd": "echo Hello, World!"
}
