name: WebApiClientService (ASP NET 8)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve the GitHub secret and decode it to a file
        env:
          HOSTNAMES: ${{ secrets.HOSTNAMES }}
        run: |
          echo $HOSTNAMES | base64 --decode > hostnames.json

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: cd WebApiClientService && dotnet restore

      - name: Build
        run: cd WebApiClientService && dotnet build --configuration Release --no-restore

      - name: Publish
        run: cd WebApiClientService && dotnet publish -c Release -o -r win-x64 --self-contained false ./publish